# Generated by Django 2.2.6 on 2020-05-25 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125)),
                ('culture', models.CharField(blank=True, max_length=255, null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('historical_note', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pori',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pori',
            name='modified_by',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='heritage_type',
            new_name='access_notes_or_rights_and_reproduction',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='accession_number',
            new_name='catalog_number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='reproduction_rights',
            new_name='digital_heritage_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='source',
            new_name='location_of_original',
        ),
        migrations.RemoveField(
            model_name='item',
            name='accession_date',
        ),
        migrations.AddField(
            model_name='collection',
            name='access_notes_or_rights_and_reproduction',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cataloge_date',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cataloger',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='citation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='historical_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='provenance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cataloge_date',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cataloger',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='citation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='historical_note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='other_forms',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_creation',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='ItemPorI',
        ),
        migrations.DeleteModel(
            name='PorI',
        ),
        migrations.AddField(
            model_name='personorinstitute',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PorIs', to='civam.Collection'),
        ),
        migrations.AddField(
            model_name='personorinstitute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PorI_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personorinstitute',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pori_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
