# Generated by Django 2.2.6 on 2020-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cover_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_images/items/'),
        ),
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
