# Generated by Django 2.2.6 on 2020-05-19 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='accession_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='accession_number',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='culture_or_community',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_creation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='external_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='heritage_type',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='physical_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='place_created',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='provenance',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reproduction_rights',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=31)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='civam.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPorI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='civam.Item')),
                ('pori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='civam.PorI')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to='civam.PorI'),
        ),
    ]
