# Generated by Django 2.2.6 on 2019-10-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='Bob', max_length=255),
            preserve_default=False,
        ),
    ]
