# Generated by Django 3.1.7 on 2021-03-22 03:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='continent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
