# Generated by Django 2.2.6 on 2020-05-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='cataloge_date',
            new_name='catalog_date',
        ),
    ]
