# Generated by Django 2.2.6 on 2020-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorinstitute',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personorinstitute',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
