# Generated by Django 2.2.6 on 2020-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20200524_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ManyToManyField(blank=True, to='civam.PersonOrInstitute'),
        ),
    ]
