# Generated by Django 3.1.7 on 2021-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20211109_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_public',
            field=models.IntegerField(blank=True, choices=[(1, 'Available To Public'), (0, 'Hidden From Public')], default=1, help_text='1: Available To Public, 0: Hidden From Public', null=True),
        ),
    ]
