# Generated by Django 2.2.6 on 2019-10-11 18:05

import constrainedfilefield.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20191011_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/jpeg'], mime_lookup_length=4096, upload_to='uploaded/'),
        ),
    ]
