# Generated by Django 2.2.6 on 2020-05-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20200526_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='catalog_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
