# Generated by Django 2.2.6 on 2019-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_images/'),
        ),
    ]
