# Generated by Django 2.2.6 on 2020-05-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20200516_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cover_image',
        ),
    ]
