# Generated by Django 2.2.6 on 2020-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0002_auto_20200527_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorinstitute',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_images/pori/'),
        ),
    ]
