# Generated by Django 3.1.7 on 2022-03-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0003_auto_20211208_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='audio',
        ),
    ]
