# Generated by Django 2.2.6 on 2020-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0003_auto_20200526_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location_of_originals',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_of_original',
        ),
        migrations.AddField(
            model_name='item',
            name='location_of_original',
            field=models.ManyToManyField(blank=True, related_name='item_locations', to='civam.PersonOrInstitute'),
        ),
    ]
