# Generated by Django 3.1.7 on 2022-03-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0004_remove_item_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoToAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('content', models.FileField(blank=True, upload_to='mp4_to_mp3/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videotoaudios', to='civam.item')),
            ],
        ),
    ]
