# Generated by Django 2.2.6 on 2020-05-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0004_auto_20200526_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
