# Generated by Django 2.2.6 on 2019-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0004_collectiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='name',
            field=models.CharField(default='bob', max_length=150),
            preserve_default=False,
        ),
    ]
