# Generated by Django 2.2.6 on 2020-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0004_auto_20200516_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cover_image',
            new_name='thumbnail',
        ),
    ]
