# Generated by Django 2.2.6 on 2020-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0005_auto_20200525_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='word',
        ),
        migrations.AddField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='hello', max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
