# Generated by Django 2.2.6 on 2020-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0005_auto_20200528_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personorinstitute',
            name='dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
