# Generated by Django 2.2.6 on 2019-11-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0005_auto_20191110_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectiongroup',
            unique_together={('name', 'collection')},
        ),
    ]
