# Generated by Django 3.1.7 on 2022-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0005_videotoaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotoaudio',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='AudioTrack',
        ),
    ]
