# Generated by Django 2.2.6 on 2020-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0005_auto_20200516_1222'),
        ('civam', '0002_auto_20200518_2353'),
    ]

    operations = [
    ]
