# Generated by Django 2.2.6 on 2020-05-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0006_auto_20200525_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='word',
        ),
    ]
