# Generated by Django 2.2.6 on 2020-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0006_auto_20200528_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
