# Generated by Django 2.2.6 on 2020-05-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0006_auto_20200519_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='creator',
        ),
    ]
