# Generated by Django 2.2.6 on 2020-05-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0007_auto_20200525_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='geographical_location',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='civam.Keyword'),
        ),
    ]
