# Generated by Django 3.1.7 on 2022-05-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0007_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetext',
            name='location',
            field=models.CharField(choices=[('ABOUT', 'About Headline'), ('MISSION', 'About: Our Mission'), ('ORIGINS', 'About: Origins'), ('PEOPLE1', 'About: People: Bio 1'), ('PEOPLE2', 'About: People: Bio 2'), ('PEOPLE3', 'About: People: Bio 3'), ('PEOPLE4', 'About: People: Bio 4'), ('PEOPLE5', 'About: People: Bio 5'), ('CONTACT', 'About: Resources & Contact Information'), ('MAP_CON', 'Map: Context for the Map, and How to use it'), ('HOME_MAP', 'Home: Simple context about the map'), ('HOME_COL', 'Home: Simple context about the collections'), ('HOME_EXP', 'Home: Simple context about the explore page'), ('COL_MORE', 'Collections: Note that more collections will be added'), ('NEWSCON', 'News: Context about the news page')], default='ABOUT', max_length=8, unique=True, verbose_name='Location of text on site'),
        ),
    ]
