# Generated by Django 2.2.6 on 2020-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0008_auto_20200525_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personorinstitute',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ManyToManyField(blank=True, related_name='collection_creators', to='civam.PersonOrInstitute'),
        ),
        migrations.AddField(
            model_name='collection',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='collection_keywords', to='civam.Keyword'),
        ),
        migrations.AddField(
            model_name='collection',
            name='location_of_originals',
            field=models.ManyToManyField(blank=True, related_name='collection_locations', to='civam.PersonOrInstitute'),
        ),
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='item_keywords', to='civam.Keyword'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location_of_originals',
            field=models.ManyToManyField(blank=True, related_name='item_locations', to='civam.PersonOrInstitute'),
        ),
    ]
