# Generated by Django 2.2.6 on 2019-10-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0009_auto_20191020_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('can_view', 'Can view an item')]},
        ),
    ]
