# Generated by Django 2.2.6 on 2020-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0009_auto_20200525_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='personorinstitute',
            name='isPerson',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
