# Generated by Django 2.2.6 on 2019-10-23 17:06

import constrainedfilefield.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0010_auto_20191020_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/jpeg'], mime_lookup_length=4096, null=True, upload_to='uploaded/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
