# Generated by Django 2.1.5 on 2019-10-23 03:17

import constrainedfilefield.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0011_auto_20191021_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/jpeg', 'image/jpg'], mime_lookup_length=4096, upload_to='uploaded/'),
        ),
    ]
