#!/bin/bash

# ADD CRON HEADER HERE!!!!

# This script is used for creating a backup file to regenerate 
# the database in case of a database failure.


# Example of usage:

# ./backupDBScript.sh

# Hardcoded Parameters:
# DB_NAME: Name of the database being backed up from Postgresql.
# BACKUP_DEST: Absolute path of where the SQL backup script will be copied to.
# FILE_SRC: Where the file is created after the pg_dump program call.
# FILE_NAME: Autogenerated file name where the date is appened to the end of the file.
# FILE_LOC: Where the file is copied from after it is created from pg_dump.

# Variables used within script
DB_NAME=django_db
BACKUP_DEST=/home/ubuntu/db-backups/DBFullBackups
FILE_SRC=/var/lib/postgresql
FILE_NAME=db_backup_$(date +%d-%m-%Y_%H-%M-%S).sql
FILE_LOC=$FILE_SRC/$FILE_NAME

postgresql_status=$(service postgresql status | grep "Active: inactive");
if [ ${#postgresql_status} -ne 0 ];
then
    if [ $EUID -ne 0 ];
    then
	echo "Postgresql is not running, requires superuser access."
	sudo "$0"
	exit "$?";
    fi
    echo "Attempting to start the postgresql...";
    service postgresql start;
    postgresql_status=$(service postgresql status | grep "Active: inactive");
    if [ ${#postgresql_status} -eq 0 ];
    then
	echo "Postgresql has sucessfully started!";
	exec sudo "$0";
    else
	echo "Failed to start postgresql!  See error below, or at 'sudo service postgresql status'";
	echo $(service postgresql status);
    fi
else
    echo "Service postgresql is running";
    # Print where database is being dumped to 
    echo "Copying $DB_NAME to $BACKUP_DEST"
    # Create file under postgres
    sudo runuser -l postgres -c "pg_dump $DB_NAME > $FILE_NAME";
    if [ -d $BACKUP_DEST ]; # Checks if destination exists
	then 	sudo cp $FILE_LOC $BACKUP_DEST; # Copying file to dest
		echo "Copied $DB_NAME to $FILE_NAME";
	# Make make path if it doesn't exist
	else	sudo runuser -l ubuntu -c 'mkdir db-backups && cd db-backups && mkdir DBFullBackups';
		sudo cp $FILE_LOC $BACKUP_DEST; # Copying file to dest
		echo "Copied $DB_NAME to $FILE_NAME";
	fi	
	echo "Copying Complete!";
fi
exit 0;
