# Generated by Django 2.2.6 on 2019-10-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0008_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_view', 'Can view an item')]},
        ),
    ]
