# Generated by Django 2.1.5 on 2019-10-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civam', '0010_auto_20191020_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
